<?php

namespace App\CarInsurance\Application\DTO;

use App\CarInsurance\Domain\Entity\GeneralData;

class GeneralDataDTO
{
    public function __construct (
        public ?string $codMedAncl,
        public ?string $condPpalEsTomador,
        public ?string $conductorUnico,
        public ?string $contrataAlgunPack,
        public ?string $cotizacion,
        public ?string $entornoOrigen,
        public ?string $fecCot,
        public ?string $fecCotAncl,
        public ?string $anosSegAnte,
        public ?string $fecUltimoSeguro,
        public ?string $franquicia,
        public ?string $idioma,
        public ?string $importeFranquicia,
        public ?string $masVehiculos,
        public ?string $mcaPagoTarjeta,
        public ?string $mediador,
        public ?string $modalidad,
        public ?string $motivoBonus,
        public ?string $motivoEstado,
        public ?string $nivelDp,
        public ?string $nivelLu,
        public ?string $nivelRc,
        public ?string $nroCochesFamilia,
        public int $nroCondOca,
        public ?string $nroOpera,
        public ?string $nroRiesgo,
        public ?string $pctOpera,
        public ?string $poliza,
        public ?string $polizaorigen,
        public ?string $polizatarificada,
        public ?string $ramo,
        public ?string $scoreA,
        public ?string $scoreB,
        public ?string $seguroEnVigor,
        public ?string $subMediador,
        public ?string $subramo,
        public ?string $suplemento,
        public ?string $tallerConcertado,
        public ?string $usuarioCot,
        public ?string $versionCot,
    ) {}

    public static function fromEntity ( GeneralData $generalData ): self {
        return new self(
            $generalData->codMedAncl()->value(),
            $generalData->condPpalEsTomador()->value(),
            $generalData->conductorUnico()->value(),
            $generalData->contrataAlgunPack()->value(),
            $generalData->cotizacion()->value(),
            $generalData->entornoOrigen()->value(),
            $generalData->fecCot()->toIso8601(),
            $generalData->fecCotAncl()->value(),
            $generalData->anosSegAnte()->value(),
            $generalData->fecUltimoSeguro()->value(),
            $generalData->franquicia()->value(),
            $generalData->idioma()->value(),
            $generalData->importeFranquicia()->value(),
            $generalData->masVehiculos()->value(),
            $generalData->mcaPagoTarjeta()->value(),
            $generalData->mediador()->value(),
            $generalData->modalidad()->value(),
            $generalData->motivoBonus()->value(),
            $generalData->motivoEstado()->value(),
            $generalData->nivelDp()->value(),
            $generalData->nivelLu()->value(),
            $generalData->nivelRc()->value(),
            $generalData->nroCochesFamilia()->value(),
            $generalData->nroCondOca()->value(),
            $generalData->nroOpera()->value(),
            $generalData->nroRiesgo()->value(),
            $generalData->pctOpera()->value(),
            $generalData->poliza()->value(),
            $generalData->polizaorigen()->value(),
            $generalData->polizatarificada()->value(),
            $generalData->ramo()->value(),
            $generalData->scoreA()->value(),
            $generalData->scoreB()->value(),
            $generalData->seguroEnVigor()->value(),
            $generalData->subMediador()->value(),
            $generalData->subramo()->value(),
            $generalData->suplemento()->value(),
            $generalData->tallerConcertado()->value(),
            $generalData->usuarioCot()->value(),
            $generalData->versionCot()->value(),
        );
    }
}
